# Allow bean definition overriding to avoid duplicate jpaAuditingHandler during startup
# spring.main.allow-bean-definition-overriding=true
spring:
    datasource:
        url: jdbc:oracle:thin:@//localhost:1521/opencbs_db
        username: opencbs
        password: OpenCBS123
        driver-class-name: oracle.jdbc.OracleDriver